INFO 2020-11-12 15:09:50,681 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:12:32,426 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\sunday\settings.py changed, reloading.
INFO 2020-11-12 15:12:33,062 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:14:19,379 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\models.py changed, reloading.
INFO 2020-11-12 15:14:19,981 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:19:25,048 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:19:25,782 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:24:30,545 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:24:31,130 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:24:42,614 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:24:43,193 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:24:53,561 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:25:02,041 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/change/ HTTP/1.1" 200 9158
INFO 2020-11-12 15:25:02,076 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:25:05,497 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5166
INFO 2020-11-12 15:25:05,515 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-12 15:25:09,859 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (question.text, date, question.date) specified for Choice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (question.text, date, question.date) specified for Choice. Check fields/fieldsets/exclude attributes of class QuestionAdmin.
ERROR 2020-11-12 15:25:09,861 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 500 133314
INFO 2020-11-12 15:25:16,582 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5166
INFO 2020-11-12 15:25:20,371 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5166
INFO 2020-11-12 15:25:20,386 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:25:21,611 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5166
INFO 2020-11-12 15:25:21,628 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:25:21,903 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5166
INFO 2020-11-12 15:25:21,916 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:26:21,967 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:26:22,569 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
WARNING 2020-11-12 15:26:29,313 [log.py:224] [log:log_response] - Not Found: /admin/polls/choice/
WARNING 2020-11-12 15:26:29,314 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 404 4228
INFO 2020-11-12 15:26:39,709 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/change/ HTTP/1.1" 200 9161
INFO 2020-11-12 15:26:43,225 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 5158
INFO 2020-11-12 15:26:43,244 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:26:45,249 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/add/ HTTP/1.1" 200 6593
INFO 2020-11-12 15:26:45,266 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:01,848 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:27:02,432 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:27:05,792 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/add/ HTTP/1.1" 200 6889
INFO 2020-11-12 15:27:05,811 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:07,700 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/add/ HTTP/1.1" 200 6889
INFO 2020-11-12 15:27:07,714 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:08,938 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5465
INFO 2020-11-12 15:27:08,955 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:10,604 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7757
INFO 2020-11-12 15:27:10,629 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:16,664 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 5454
INFO 2020-11-12 15:27:16,683 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:18,428 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/add/ HTTP/1.1" 200 6889
INFO 2020-11-12 15:27:18,449 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:29,991 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/question/add/ HTTP/1.1" 302 0
INFO 2020-11-12 15:27:30,035 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6819
INFO 2020-11-12 15:27:30,059 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:32,813 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5465
INFO 2020-11-12 15:27:32,843 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:33,882 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:27:33,899 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:36,567 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5465
INFO 2020-11-12 15:27:36,594 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:37,901 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7800
INFO 2020-11-12 15:27:37,918 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:27:46,793 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/add/?_to_field=id&_popup=1 HTTP/1.1" 200 3677
INFO 2020-11-12 15:27:46,807 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-12 15:28:09,778 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type tuple)
ERROR 2020-11-12 15:28:09,779 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/choice/add/ HTTP/1.1" 500 113767
INFO 2020-11-12 15:28:32,734 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7800
INFO 2020-11-12 15:28:34,940 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 5465
INFO 2020-11-12 15:28:37,021 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7800
INFO 2020-11-12 15:28:37,039 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-12 15:28:42,407 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 814, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type tuple)
ERROR 2020-11-12 15:28:42,408 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/choice/add/ HTTP/1.1" 500 113767
INFO 2020-11-12 15:29:30,650 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\models.py changed, reloading.
INFO 2020-11-12 15:29:31,249 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:29:36,679 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7800
INFO 2020-11-12 15:29:38,116 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7800
INFO 2020-11-12 15:29:38,131 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:42,747 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/choice/add/ HTTP/1.1" 302 0
INFO 2020-11-12 15:29:42,789 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6823
INFO 2020-11-12 15:29:42,808 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:51,975 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:29:52,001 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:52,886 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:29:52,912 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:53,885 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:29:53,901 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:54,901 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:29:54,923 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:55,661 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:29:55,685 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:56,392 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:29:56,418 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:57,054 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:29:57,084 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:29:57,734 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:29:57,766 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:30:23,985 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:30:24,591 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:30:26,277 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
WARNING 2020-11-12 15:30:26,744 [log.py:224] [log:log_response] - Not Found: /admin/polls/question/
WARNING 2020-11-12 15:30:26,744 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 404 4232
INFO 2020-11-12 15:30:27,319 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
WARNING 2020-11-12 15:30:29,050 [log.py:224] [log:log_response] - Not Found: /admin/polls/question/
WARNING 2020-11-12 15:30:29,050 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 404 4232
WARNING 2020-11-12 15:30:29,831 [log.py:224] [log:log_response] - Not Found: /admin/polls/question/
WARNING 2020-11-12 15:30:29,831 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 404 4232
INFO 2020-11-12 15:30:31,001 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
INFO 2020-11-12 15:30:31,717 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
ERROR 2020-11-12 15:30:32,078 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (question.date, date, question.text) specified for Choice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (question.date, date, question.text) specified for Choice. Check fields/fieldsets/exclude attributes of class QuestionAdmin.
ERROR 2020-11-12 15:30:32,081 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 500 133314
INFO 2020-11-12 15:30:32,296 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
INFO 2020-11-12 15:30:35,802 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 7086
INFO 2020-11-12 15:30:37,929 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
INFO 2020-11-12 15:30:37,951 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-12 15:30:41,655 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (question.date, date, question.text) specified for Choice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (question.date, date, question.text) specified for Choice. Check fields/fieldsets/exclude attributes of class QuestionAdmin.
ERROR 2020-11-12 15:30:41,656 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 500 133314
INFO 2020-11-12 15:39:59,806 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:40:00,401 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:40:12,849 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:40:13,484 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:40:58,769 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:40:59,372 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:41:02,177 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 7086
INFO 2020-11-12 15:41:03,619 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
INFO 2020-11-12 15:41:03,650 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-12 15:41:06,078 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (vote) specified for Choice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (vote) specified for Choice. Check fields/fieldsets/exclude attributes of class QuestionAdmin.
ERROR 2020-11-12 15:41:06,080 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 500 132803
INFO 2020-11-12 15:41:08,744 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
INFO 2020-11-12 15:41:16,730 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/choice/ HTTP/1.1" 302 0
INFO 2020-11-12 15:41:16,759 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6509
INFO 2020-11-12 15:41:16,783 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:16,803 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
INFO 2020-11-12 15:41:21,593 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6331
INFO 2020-11-12 15:41:21,617 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-12 15:41:24,399 [log.py:224] [log:log_response] - Internal Server Error: /admin/polls/choice/3/change/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (vote) specified for Choice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (vote) specified for Choice. Check fields/fieldsets/exclude attributes of class QuestionAdmin.
ERROR 2020-11-12 15:41:24,400 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/3/change/ HTTP/1.1" 500 133404
INFO 2020-11-12 15:41:32,553 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\admin.py changed, reloading.
INFO 2020-11-12 15:41:33,178 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:41:35,733 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/3/change/ HTTP/1.1" 200 8008
INFO 2020-11-12 15:41:35,763 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:37,574 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:41:37,591 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:39,040 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:41:39,057 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:39,949 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:41:39,966 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:40,933 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:41:40,962 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:41,575 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:41:41,592 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:42,157 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:41:42,183 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:45,325 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:41:45,351 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:41:51,401 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/3/change/ HTTP/1.1" 200 8008
INFO 2020-11-12 15:41:51,419 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
WARNING 2020-11-12 15:42:04,517 [log.py:224] [log:log_response] - Not Found: /
WARNING 2020-11-12 15:42:04,518 [basehttp.py:157] [basehttp:log_message] - "GET / HTTP/1.1" 404 2238
INFO 2020-11-12 15:42:10,326 [basehttp.py:157] [basehttp:log_message] - "GET /polls HTTP/1.1" 301 0
INFO 2020-11-12 15:42:10,333 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 219
ERROR 2020-11-12 15:42:13,338 [log.py:224] [log:log_response] - Internal Server Error: /polls/1/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: detail() got an unexpected keyword argument 'pk'
ERROR 2020-11-12 15:42:13,339 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/ HTTP/1.1" 500 63775
INFO 2020-11-12 15:42:38,848 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6621
INFO 2020-11-12 15:42:38,877 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:42:43,650 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/add/ HTTP/1.1" 200 6889
INFO 2020-11-12 15:42:43,671 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:42:57,666 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/question/add/ HTTP/1.1" 302 0
INFO 2020-11-12 15:42:57,707 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 7038
INFO 2020-11-12 15:42:57,728 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:44:58,576 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\urls.py changed, reloading.
INFO 2020-11-12 15:44:59,170 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:45:08,570 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
INFO 2020-11-12 15:45:10,190 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
INFO 2020-11-12 15:45:10,662 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
INFO 2020-11-12 15:45:10,867 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
ERROR 2020-11-12 15:45:12,166 [log.py:224] [log:log_response] - Internal Server Error: /polls/2/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\urls\base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'polls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\polls\views.py", line 17, in detail
    return render(request, 'polls/detail.html', {'question': question})
  File "D:\python\sunday\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\python\sunday\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\python\sunday\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\sunday\venv\lib\site-packages\django\urls\base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'polls' is not a registered namespace
ERROR 2020-11-12 15:45:12,167 [basehttp.py:157] [basehttp:log_message] - "GET /polls/2/ HTTP/1.1" 500 118772
INFO 2020-11-12 15:46:15,479 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\sunday\urls.py changed, reloading.
INFO 2020-11-12 15:46:16,077 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:46:51,085 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\sunday\urls.py changed, reloading.
INFO 2020-11-12 15:46:51,659 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
ERROR 2020-11-12 15:46:54,239 [log.py:224] [log:log_response] - Internal Server Error: /polls/2/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\urls\base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'polls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\polls\views.py", line 17, in detail
    return render(request, 'polls/detail.html', {'question': question})
  File "D:\python\sunday\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\python\sunday\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\python\sunday\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\python\sunday\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\sunday\venv\lib\site-packages\django\urls\base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'polls' is not a registered namespace
ERROR 2020-11-12 15:46:54,241 [basehttp.py:157] [basehttp:log_message] - "GET /polls/2/ HTTP/1.1" 500 118909
INFO 2020-11-12 15:47:49,480 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\urls.py changed, reloading.
INFO 2020-11-12 15:47:50,128 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:47:57,711 [basehttp.py:157] [basehttp:log_message] - "GET /polls/2/ HTTP/1.1" 200 373
INFO 2020-11-12 15:48:08,507 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/ HTTP/1.1" 200 489
INFO 2020-11-12 15:48:16,753 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/ HTTP/1.1" 200 6837
INFO 2020-11-12 15:48:16,782 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:18,099 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/question/1/change/ HTTP/1.1" 200 7147
INFO 2020-11-12 15:48:18,118 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:19,870 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 6630
INFO 2020-11-12 15:48:19,896 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:27,166 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7846
INFO 2020-11-12 15:48:27,182 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:37,477 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/choice/add/ HTTP/1.1" 302 0
INFO 2020-11-12 15:48:37,518 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 7028
INFO 2020-11-12 15:48:37,534 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:39,253 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/add/ HTTP/1.1" 200 7846
INFO 2020-11-12 15:48:39,281 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:53,263 [basehttp.py:157] [basehttp:log_message] - "POST /admin/polls/choice/add/ HTTP/1.1" 302 0
INFO 2020-11-12 15:48:53,306 [basehttp.py:157] [basehttp:log_message] - "GET /admin/polls/choice/ HTTP/1.1" 200 7233
INFO 2020-11-12 15:48:53,320 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-12 15:48:56,093 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
INFO 2020-11-12 15:48:57,094 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/ HTTP/1.1" 200 727
ERROR 2020-11-12 15:49:13,856 [log.py:224] [log:log_response] - Internal Server Error: /polls/1/vote/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
TypeError: vote() got an unexpected keyword argument 'pk'
ERROR 2020-11-12 15:49:13,857 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 500 68983
INFO 2020-11-12 15:50:27,850 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\urls.py changed, reloading.
INFO 2020-11-12 15:50:28,454 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:51:42,466 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
INFO 2020-11-12 15:51:43,061 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
ERROR 2020-11-12 15:51:49,078 [log.py:224] [log:log_response] - Internal Server Error: /polls/1/vote/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\python\sunday\polls\views.py", line 29, in vote
    return HttpResponseRedirect(reversed('polls.result', args=(question.id,)))
TypeError: reversed() takes no keyword arguments
ERROR 2020-11-12 15:51:49,079 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 500 72802
INFO 2020-11-12 15:52:02,585 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
INFO 2020-11-12 15:52:03,660 [basehttp.py:157] [basehttp:log_message] - "GET /polls/2/ HTTP/1.1" 200 375
INFO 2020-11-12 15:52:07,308 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/ HTTP/1.1" 200 729
ERROR 2020-11-12 15:52:09,777 [log.py:224] [log:log_response] - Internal Server Error: /polls/1/vote/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\python\sunday\polls\views.py", line 29, in vote
    return HttpResponseRedirect(reversed('polls.result', args=(question.id,)))
TypeError: reversed() takes no keyword arguments
ERROR 2020-11-12 15:52:09,778 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 500 72802
INFO 2020-11-12 15:52:27,516 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
INFO 2020-11-12 15:52:28,094 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
ERROR 2020-11-12 15:52:33,017 [log.py:224] [log:log_response] - Internal Server Error: /polls/1/vote/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\python\sunday\polls\views.py", line 29, in vote
    return HttpResponseRedirect(reversed('polls.result', args=(pk,)))
TypeError: reversed() takes no keyword arguments
ERROR 2020-11-12 15:52:33,018 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 500 72784
INFO 2020-11-12 15:53:36,366 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result HTTP/1.1" 301 0
INFO 2020-11-12 15:53:36,382 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 319
INFO 2020-11-12 15:54:44,129 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
INFO 2020-11-12 15:54:44,714 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:55:10,543 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
INFO 2020-11-12 15:55:11,146 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:56:23,415 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/ HTTP/1.1" 200 729
ERROR 2020-11-12 15:56:25,970 [log.py:224] [log:log_response] - Internal Server Error: /polls/1/vote/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\python\sunday\polls\views.py", line 30, in vote
    return HttpResponseRedirect(reverse('polls.result', args=(pk,)))
  File "D:\python\sunday\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\python\sunday\venv\lib\site-packages\django\urls\resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'polls.result' not found. 'polls.result' is not a valid view function or pattern name.
ERROR 2020-11-12 15:56:25,972 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 500 83243
INFO 2020-11-12 15:57:18,901 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
INFO 2020-11-12 15:57:19,540 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 15:57:24,423 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 302 0
INFO 2020-11-12 15:57:24,447 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 319
INFO 2020-11-12 15:57:31,547 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 302 0
INFO 2020-11-12 15:57:31,563 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 319
INFO 2020-11-12 15:57:36,073 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 302 0
INFO 2020-11-12 15:57:36,081 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 319
INFO 2020-11-12 15:57:40,354 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 302 0
INFO 2020-11-12 15:57:40,371 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 318
INFO 2020-11-12 15:58:20,333 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
INFO 2020-11-12 15:58:20,910 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-12 16:03:04,915 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 302 0
INFO 2020-11-12 16:03:04,935 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 629
INFO 2020-11-12 16:04:02,674 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 469
WARNING 2020-11-12 16:05:43,639 [log.py:224] [log:log_response] - Not Found: /
WARNING 2020-11-12 16:05:43,640 [basehttp.py:157] [basehttp:log_message] - "GET / HTTP/1.1" 404 2238
INFO 2020-11-12 16:05:50,902 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/ HTTP/1.1" 200 729
INFO 2020-11-12 16:05:52,992 [basehttp.py:157] [basehttp:log_message] - "POST /polls/1/vote/ HTTP/1.1" 302 0
INFO 2020-11-12 16:05:52,998 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 741
INFO 2020-11-12 16:06:27,968 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 695
INFO 2020-11-12 16:06:29,766 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 695
INFO 2020-11-12 16:06:30,411 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 695
INFO 2020-11-12 16:06:30,819 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 695
INFO 2020-11-12 16:06:39,496 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 741
INFO 2020-11-12 16:07:04,454 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 1070
INFO 2020-11-12 16:07:05,523 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 1070
INFO 2020-11-12 16:07:05,938 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 1070
INFO 2020-11-12 16:07:06,260 [basehttp.py:157] [basehttp:log_message] - "GET /polls/1/result/ HTTP/1.1" 200 1070
INFO 2020-11-12 16:07:42,805 [basehttp.py:157] [basehttp:log_message] - "GET /index/ HTTP/1.1" 200 5
WARNING 2020-11-12 16:07:51,301 [log.py:224] [log:log_response] - Not Found: /polls/index
WARNING 2020-11-12 16:07:51,301 [basehttp.py:157] [basehttp:log_message] - "GET /polls/index HTTP/1.1" 404 2909
INFO 2020-11-12 16:07:51,458 [basehttp.py:157] [basehttp:log_message] - "GET /polls/ HTTP/1.1" 200 289
INFO 2020-11-12 16:08:02,816 [basehttp.py:157] [basehttp:log_message] - "GET /polls/2/ HTTP/1.1" 200 375
INFO 2020-11-12 16:08:19,811 [basehttp.py:157] [basehttp:log_message] - "POST /polls/2/vote/ HTTP/1.1" 200 12
INFO 2020-11-12 16:09:14,267 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\polls\views.py changed, reloading.
