INFO 2020-11-11 17:05:58,844 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:06:07,321 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2246
INFO 2020-11-11 17:06:15,798 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2246
INFO 2020-11-11 17:06:22,021 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2246
INFO 2020-11-11 17:06:28,261 [basehttp.py:157] [basehttp:log_message] - "GET /admin/logout/ HTTP/1.1" 200 1498
INFO 2020-11-11 17:06:31,294 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:06:31,308 [basehttp.py:157] [basehttp:log_message] - "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2196
INFO 2020-11-11 17:06:38,255 [basehttp.py:157] [basehttp:log_message] - "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:06:38,281 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:06:46,856 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:06:46,888 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4257
INFO 2020-11-11 17:06:46,893 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:06:46,895 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
INFO 2020-11-11 17:06:46,961 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2020-11-11 17:06:46,961 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2020-11-11 17:06:46,961 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2020-11-11 17:06:46,962 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2020-11-11 17:07:22,576 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:07:29,018 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/ HTTP/1.1" 200 2746
INFO 2020-11-11 17:07:31,326 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:07:33,675 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 4400
INFO 2020-11-11 17:07:33,695 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/css/changelists.css HTTP/1.1" 200 6281
INFO 2020-11-11 17:07:33,709 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:07:33,737 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2020-11-11 17:07:41,747 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:07:43,501 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:07:52,363 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:08:01,371 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 4400
INFO 2020-11-11 17:08:01,391 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:08:05,884 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:08:09,755 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 4400
INFO 2020-11-11 17:08:09,778 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:08:15,052 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:08:16,777 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:08:16,795 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-11 17:08:40,343 [log.py:224] [log:log_response] - Internal Server Error: /admin/auth/group/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 810, in log_addition
    return LogEntry.objects.log_action(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\models.py", line 29, in log_action
    return self.model.objects.create(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
ERROR 2020-11-11 17:08:40,347 [basehttp.py:157] [basehttp:log_message] - "POST /admin/auth/group/add/ HTTP/1.1" 500 274885
INFO 2020-11-11 17:10:44,562 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
ERROR 2020-11-11 17:10:53,843 [log.py:224] [log:log_response] - Internal Server Error: /admin/auth/group/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 810, in log_addition
    return LogEntry.objects.log_action(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\models.py", line 29, in log_action
    return self.model.objects.create(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
ERROR 2020-11-11 17:10:53,848 [basehttp.py:157] [basehttp:log_message] - "POST /admin/auth/group/add/ HTTP/1.1" 500 274752
INFO 2020-11-11 17:14:13,332 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:14:14,487 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:14:15,299 [basehttp.py:157] [basehttp:log_message] - "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:14:15,315 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:14:20,467 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:14:20,488 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-11 17:14:27,007 [log.py:224] [log:log_response] - Internal Server Error: /admin/auth/group/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 810, in log_addition
    return LogEntry.objects.log_action(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\models.py", line 29, in log_action
    return self.model.objects.create(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
ERROR 2020-11-11 17:14:27,010 [basehttp.py:157] [basehttp:log_message] - "POST /admin/auth/group/add/ HTTP/1.1" 500 274885
INFO 2020-11-11 17:15:01,579 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:15:09,648 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
WARNING 2020-11-11 17:15:15,054 [log.py:224] [log:log_response] - Not Found: /
WARNING 2020-11-11 17:15:15,054 [basehttp.py:157] [basehttp:log_message] - "GET / HTTP/1.1" 404 2132
INFO 2020-11-11 17:15:22,332 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:15:24,559 [basehttp.py:157] [basehttp:log_message] - "GET /admin/password_change/ HTTP/1.1" 200 3761
INFO 2020-11-11 17:15:28,710 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:15:36,721 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 4400
INFO 2020-11-11 17:15:36,742 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:15:41,999 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7546
INFO 2020-11-11 17:15:42,018 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:15:55,460 [basehttp.py:157] [basehttp:log_message] - "POST /admin/auth/group/add/ HTTP/1.1" 200 7695
INFO 2020-11-11 17:15:55,480 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
ERROR 2020-11-11 17:16:01,406 [log.py:224] [log:log_response] - Internal Server Error: /admin/auth/group/add/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 810, in log_addition
    return LogEntry.objects.log_action(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\models.py", line 29, in log_action
    return self.model.objects.create(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\sunday\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "D:\python\sunday\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\sunday\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test`.`django_admin_log`, CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
ERROR 2020-11-11 17:16:01,409 [basehttp.py:157] [basehttp:log_message] - "POST /admin/auth/group/add/ HTTP/1.1" 500 274884
INFO 2020-11-11 17:23:14,085 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:23:15,026 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:23:15,093 [basehttp.py:157] [basehttp:log_message] - "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2196
INFO 2020-11-11 17:23:25,234 [basehttp.py:157] [basehttp:log_message] - "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:23:25,261 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 2857
INFO 2020-11-11 17:23:27,676 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/add/ HTTP/1.1" 200 7299
INFO 2020-11-11 17:23:27,699 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:23:35,250 [basehttp.py:157] [basehttp:log_message] - "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2020-11-11 17:23:35,306 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 5727
INFO 2020-11-11 17:23:35,327 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:23:35,345 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2020-11-11 17:23:40,433 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/change/ HTTP/1.1" 200 7522
INFO 2020-11-11 17:23:40,461 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:23:51,843 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/ HTTP/1.1" 200 2746
INFO 2020-11-11 17:23:56,813 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/ HTTP/1.1" 200 2746
INFO 2020-11-11 17:23:58,971 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 5545
INFO 2020-11-11 17:23:58,991 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:24:01,121 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/change/ HTTP/1.1" 200 7522
INFO 2020-11-11 17:24:01,153 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:24:11,698 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/history/ HTTP/1.1" 200 3338
INFO 2020-11-11 17:30:25,980 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:30:26,671 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:30:40,899 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/change/ HTTP/1.1" 200 8045
INFO 2020-11-11 17:30:42,068 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/ HTTP/1.1" 200 6068
INFO 2020-11-11 17:30:42,990 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/ HTTP/1.1" 200 2746
INFO 2020-11-11 17:30:44,671 [basehttp.py:157] [basehttp:log_message] - "GET /admin/auth/group/1/change/ HTTP/1.1" 200 8045
INFO 2020-11-11 17:30:46,205 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 3823
INFO 2020-11-11 17:30:48,564 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 3823
INFO 2020-11-11 17:30:50,423 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 3823
INFO 2020-11-11 17:30:51,110 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 3823
INFO 2020-11-11 17:30:54,929 [basehttp.py:157] [basehttp:log_message] - "GET /admin/logout/ HTTP/1.1" 200 1498
INFO 2020-11-11 17:30:57,421 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:30:57,431 [basehttp.py:157] [basehttp:log_message] - "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2196
INFO 2020-11-11 17:31:08,076 [basehttp.py:157] [basehttp:log_message] - "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2020-11-11 17:31:08,105 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 3823
INFO 2020-11-11 17:31:17,114 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 5807
INFO 2020-11-11 17:31:17,139 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:31:18,648 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/1/change/ HTTP/1.1" 200 14939
INFO 2020-11-11 17:31:18,669 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:31:18,677 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/js/calendar.js HTTP/1.1" 200 7788
INFO 2020-11-11 17:31:18,686 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19750
INFO 2020-11-11 17:31:18,732 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2020-11-11 17:31:18,733 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2020-11-11 17:31:55,266 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/1/change/ HTTP/1.1" 302 0
INFO 2020-11-11 17:31:55,297 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 5999
INFO 2020-11-11 17:31:55,314 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:32:55,973 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/add/ HTTP/1.1" 200 14577
INFO 2020-11-11 17:32:56,004 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:33:41,906 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 302 0
INFO 2020-11-11 17:33:41,937 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 6213
INFO 2020-11-11 17:33:41,967 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:40:22,114 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:40:22,728 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:40:30,350 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/add/ HTTP/1.1" 200 7056
INFO 2020-11-11 17:40:30,370 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:40:39,712 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 8775
INFO 2020-11-11 17:40:39,746 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2020-11-11 17:40:39,750 [basehttp.py:157] [basehttp:log_message] - "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2020-11-11 17:40:41,625 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 8775
INFO 2020-11-11 17:40:41,650 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:40:52,400 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/add/ HTTP/1.1" 200 7056
INFO 2020-11-11 17:40:52,437 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:41:08,607 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 7313
INFO 2020-11-11 17:41:08,630 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:41:18,705 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 7244
INFO 2020-11-11 17:41:18,723 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:41:31,716 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 302 0
ERROR 2020-11-11 17:41:31,779 [log.py:224] [log:log_response] - Internal Server Error: /admin/user/userinfo/3/change/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for UserInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\auth\admin.py", line 80, in get_form
    return super().get_form(request, obj, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for UserInfo. Check fields/fieldsets/exclude attributes of class UserAdmin.
ERROR 2020-11-11 17:41:31,781 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/3/change/ HTTP/1.1" 500 143020
INFO 2020-11-11 17:46:48,468 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\models.py changed, reloading.
INFO 2020-11-11 17:46:49,092 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:47:47,516 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:47:48,142 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:50:59,281 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:50:59,869 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:52:16,736 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:52:17,321 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:55:15,110 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:55:15,699 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:57:02,143 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
INFO 2020-11-11 17:57:02,778 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:57:36,913 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 17:57:46,416 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 4926
INFO 2020-11-11 17:57:46,534 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 4697
INFO 2020-11-11 17:57:48,517 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 9165
INFO 2020-11-11 17:57:48,547 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:57:51,951 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/add/ HTTP/1.1" 200 7056
INFO 2020-11-11 17:57:51,978 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:58:08,255 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 7229
INFO 2020-11-11 17:58:08,271 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:58:25,224 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 7255
INFO 2020-11-11 17:58:25,240 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 17:58:33,821 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 302 0
ERROR 2020-11-11 17:58:33,873 [log.py:224] [log:log_response] - Internal Server Error: /admin/user/userinfo/4/change/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for UserInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\auth\admin.py", line 80, in get_form
    return super().get_form(request, obj, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for UserInfo. Check fields/fieldsets/exclude attributes of class UserProfileAdmin.
ERROR 2020-11-11 17:58:33,875 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/4/change/ HTTP/1.1" 500 142928
INFO 2020-11-11 18:01:55,233 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\admin.py changed, reloading.
